import type { Metadata } from 'next';
import { Jost } from 'next/font/google';

import './globals.css';

const jost = Jost({
  variable: '--font-jost',
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={jost.variable} lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
